apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Values.deployment.name }}"
  namespace: flask-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-{{ .Values.deployment.label }}"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-{{ .Values.deployment.label }}"
    spec:
      containers:
      - name: flaskapp-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.containerPort }}
        env:
            - name: DATABASE
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Release.Name }}-{{ .Values.configMap.name }}"
                  key: MY_DATABASE
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-{{ .Values.secret.name }}"
                  key: MY_USERNAME
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-{{ .Values.secret.name }}"
                  key: MY_PASSWORD