apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Values.service.name }}"
  namespace: flask-app
spec:
  selector:
    app: "{{ .Release.Name }}-{{ .Values.service.selector }}"
  type: {{ .Values.service.type }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}